name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: Check for Dockerfile changes
        id: dockerfile
        run: echo changed=$(if git diff --name-only HEAD~1 | grep -qE 'Dockerfile(\.[^/]+)?$'; then echo true; else echo false; fi) >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        if: steps.dockerfile.outputs.changed == 'true'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker images
        if: steps.dockerfile.outputs.changed == 'true'
        run: |
          set -e
          for file in $(git diff --name-only HEAD~1 | grep -E 'Dockerfile(\.[^/]+)?$'); do
            tag=$(basename "$(dirname "$file")")
            docker build --pull . -f "$file" -t mirzamk/crud:"$tag"
            docker push mirzamk/crud:"$tag"
          done